rules:
  - url_pattern: "^https?://example\\.com/.*"
    action: "block"
  - url_pattern: "^https?://modify\\.example\\.com/.*"
    action: "modify"
    modifications:
      - type: "add_header"
        key: "X-Custom-Header"
        value: "CustomValue"
      - type: "remove_header"
        key: "Referer"
      - type: "set_header"
        key: "User-Agent"
        value: "CustomUserAgent"
